version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: wdc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wdc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: wdc-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: wdc_db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
